name: PR Check

on:
  pull_request:
    branches:
      - main  
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      TF_VERSION: '1.9.7'  
      TF_WORKING_DIR: '.'  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      continue-on-error: true