name: Terraform CI

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Check Terraform formatting
      if: steps.fmt.outcome == 'failure'
      run: exit 1